services:
#  master-data-service:
#    build: .
#    ports:
#      - "3004:3004"
#    environment:
#      PORT: 3004
#      DB_HOST: master-data-db
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: master_data_db
#    depends_on:
#      master-data-db:
#        condition: service_healthy

  master-data-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master_data_db
    ports:
      - "54324:5432"
    volumes:
      - master_data_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  master_data_db_data:
